config/routes.rb
Rails.application.routes.draw do

  get 'ideas/index'

  get 'ideas/create'

  get 'ideas/show'

  post "like" => 'ideas#like'

  get 'sessions/create'
  get 'logout' => 'sessions#logout'

  root 'users#index'

  resources :users, only: [:show, :create]
  resources :ideas, only: [:index, :show, :create]

  post 'sessions' => 'sessions#create'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  validates :idea, :user_id, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :likes
  has_many :ideas
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :name, :alias, presence: true, length: { in: 2..20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def create
    idea = Idea.new(idea_params)

    if idea.save
      #redirect to this page
      redirect_to ideas_path
    else
      flash[:errors] = idea.errors.full_messages
      redirect_to :back
    end
  end
  
  def like

  end

  def show
    @idea = Idea.find(params[:id])
  end
  private
    def idea_params
      params.require(:idea).permit(:idea, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create 
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to ideas_path
    else
      flash[:errors] = ["Invalid Email / Password Combination"]
      redirect_to :back
    end
  end

  def logout
    reset_session
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @ideas = User.joins(:ideas).select("COUNT(ideas.id) as count").find(params[:id])
  end

  def index
  end

  def create
    user = User.new(user_params)

    if user.save
      # go to success page
      session[:user_id] = user.id
      redirect_to ideas_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to :back
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :alias, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/index.html.erb
<div class="container">
    <a href="/logout">Logout</a>
    <h3>Hi <%= User.find(session[:user_id]).name %>!</h3>
    
    <br>
    <br>
    <form action="/ideas" method="post">
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
    <textarea placeholder="Post Something witty" name="idea[idea]" cols="50" rows="5"></textarea>
    <input type="hidden" name="idea[user_id]" value="<%= session[:user_id] %>">
    <input type="submit" value="Idea!" class="btn btn-primary">
    </form>

    <% @ideas.each do |i| %>
    <div>
        <p><a href="/users/<%= User.find(i.user_id).id %>"><%= User.find(i.user_id).name %></a> says:</p>
        <p class="border border-dark"><%= i.idea %></p>
        <p><a href="">Like</a> <a href="<%= idea_path(i.id) %>">number of people</a></p>
    </div>
    <% end %>
</div>

app/views/ideas/show.html.erb
<div class="container">
        <a href="<%= ideas_index_path %>">Bright Ideas</a> <a href="/logout">Logout</a>
        <p>
            <a href=""><%= User.find(@idea.user_id).name %></a> Says:
            <div class="border">
                <p><%= @idea.idea %></p>
            </div>
        </p>
        <h4>People who liked this post:</h4>
        <table class="table table-striped">
            <thead>
                <tr>
                <th>Alias</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
                <%  @idea.users.each do |u| %>
                <tr>
                    <td><%= u.alias %></td>
                    <td><%= u.name %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrightIdeas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <% if flash[:errors] %>
      <% flash[:errors].each do |e| %>
        <p><%= e %></p>
        <% end %>
    <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class="container">
    <h2>Welcome</h2>
    <div class="row">
        <div class="col-md-6 border">
            <h3>Resgister</h3>
            <form action="/users" method="post">
            <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
            <p><label for="name">Name:</label> <input type="text" name="user[name]"></p>
            <p><label for="alias">Alias:</label> <input type="text" name="user[alias]"></p>
            <p><label for="email">Email:</label> <input type="email" name="user[email]"></p>
            <p><label for="password">Password:</label> <input type="password" name="user[password]"></p>
            <p><label for="password_confirmation">Password Confirmation:</label> <input type="password" name="user[password_confirmation]"></p>
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    </div>
    <div class="col-md-6 border">
        <h3>Login</h3>
        <form action="/sessions" method="post">
            <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
            <p><label for="email">Email:</label> <input type="email" name="email"></p>
            <p><label for="password">Password</label> <input type="password" name="password"></p>
            <input type="submit" value="Login" class="btn btn-primary">
            
            </form>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <a href="<%= ideas_index_path %>">Bright Ideas</a> <a href="/logout">Logout</a>
    <p>Name: <%= User.find(@user.id).name %></p>
    <p>Alias: <%= User.find(@user.id).alias %></p>
    <p>Email: <%= User.find(@user.id).email %></p>

    <hr>

    <p>Total Number of Post: <%= @ideas.count %></p>
    <p>Total Number of Likes: </p>
</div>